language: php

matrix:
    include:
        - php: 7.4snapshot
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.4snapshot
        - php: 7.4snapshot
          env: PHPUNIT_FLAGS="--coverage-text"
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly

services:
    - postgresql

before_script:
    - psql -c 'CREATE DATABASE doctrine_postgres_bundle;' -U postgres
    - psql -c "CREATE USER doctrine_postgres_bundle WITH ENCRYPTED PASSWORD 'doctrine_postgres_bundle';" -U postgres
    - psql -c 'ALTER DATABASE doctrine_postgres_bundle OWNER TO doctrine_postgres_bundle;' -U postgres
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit $PHPUNIT_FLAGS

cache:
    directories:
        - $COMPOSER_CACHE_DIR
